### PR TITLE
Updated phone number

### LINKED ISSUE #231: Update the phone number in the bottom of the readme.md file
**Is your feature request related to a problem? Please describe.**
Currently, there is a wrong phone number

**Describe the solution you'd like**
Add my new phone number as +94 72 825 9003

**Are you work on this?**
No

### PR DESCRIPTION
**Pull request by Vaishnavi-More**
## Purpose

The purpose of this Pull Request is to fix #231 

## Goals

Updating phone number

## Approach

Updated phone number

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Remove the screenshot section in pr template @Vaishnavi-More

**Review by YoshithaRathnayake — CHANGES_REQUESTED** [review]
Remove the Preview Link section in pr template @Vaishnavi-More

**Comment by Vaishnavi-More** [comment]
Hey @YoshithaRathnayake will you just let me know what actually I have to do?
Actually I have made changes in your phone number, do you need more changes in your read me file?
I am a beginner so I have just made changes in read me file according to the issue open.
Thank you!

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake will you just let me know what actually I have to do? Actually I have made changes in your phone number, do you need more changes in your read me file? I am a beginner so I have just made changes in read me file according to the issue open. Thank you!

Ok then I will do the changes wanted @Vaishnavi-More

**Comment by Vaishnavi-More** [comment]
Hey @YoshithaRathnayake you just guide me how to remove screenshot from PR template so that I'll do the changes and I'll also learn new thing and your work will also be done!

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake you just guide me how to remove screenshot from PR template so that I'll do the changes and I'll also learn new thing and your work will also be done!

It's a big thing so I did that ok? @Vaishnavi-More

**Review by YoshithaRathnayake — APPROVED** [review]
Good Job !
Thank You @Vaishnavi-More

**Comment by Vaishnavi-More** [comment]
> > Hey @YoshithaRathnayake you just guide me how to remove screenshot from PR template so that I'll do the changes and I'll also learn new thing and your work will also be done!
> 
> It's a big thing so I did that ok? @Vaishnavi-More

okay!
Thank you for understanding and helping me out!

**Comment by Vaishnavi-More** [comment]
Hey @YoshithaRathnayake can I ask you one doubt?

**Comment by YoshithaRathnayake** [comment]
> Hey @YoshithaRathnayake can I ask you one doubt?

Yes tell me @Vaishnavi-More

**Comment by Vaishnavi-More** [comment]
Now you have merged my request and earlier my two other request are also merged but I am not able to see progress on Hacktoberfest page, and it is showing me waiting. So do you have any idea how much time it will take to update?

**Comment by YoshithaRathnayake** [comment]
> Now you have merged my request and earlier my two other request are also merged but I am not able to see progress on Hacktoberfest page, and it is showing me waiting. So do you have any idea how much time it will take to update?

Yes it's taking 7 days to accept I did it correctly but I don't know about the other one that merged your two PRs @Vaishnavi-More

**Comment by YoshithaRathnayake** [comment]
> Now you have merged my request and earlier my two other request are also merged but I am not able to see progress on Hacktoberfest page, and it is showing me waiting. So do you have any idea how much time it will take to update?

can you go to this page and create a new discussion [https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/discussions/new](https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/discussions/new) and ask the question you want here and click the button 'start discussion' @Vaishnavi-More

**Comment by YoshithaRathnayake** [comment]
https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE/discussions/118#discussioncomment-3940123

So I put the answer is there a option to mark the answer correct, if its there pls put correct that will help me and you too much @Vaishnavi-More Please do this!

**Pull request merged**
