### PR TITLE
Add a full stop at the end of the fourth sentence in About section

### LINKED ISSUE #358: Add a full stop for the fourth sentence in About section
Add a full stop for the fourth sentence in About section

### PR DESCRIPTION
**Pull request by harshvyas-22**
Add a full stop at the end of the fourth sentence in About section

### CODE REVIEW

**Comment by harshvyas-22** [comment]
done

**Comment by harshvyas-22** [comment]
done

**Review by YoshithaRathnayake — APPROVED** [review]
Thank You!

**Comment by YoshithaRathnayake** [comment]
Now delete the branch @harshvyas-22

**Comment by harshvyas-22** [comment]
can i do more?

**Pull request merged**
